"""initial schema

Revision ID: f3b079cf1d75
Revises: 
Create Date: 2026-06-22 02:27:03.972870
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f3b079cf1d75'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_id', name='uq_repo_provider_id')
    )
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repositories_provider'), ['provider'], unique=False)

    op.create_table('pull_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repo_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_pr_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('merged_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('source_branch', sa.String(length=512), nullable=False),
    sa.Column('target_branch', sa.String(length=512), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=False),
    sa.Column('base_commit_sha', sa.String(length=64), nullable=False),
    sa.Column('jira_issue_id', sa.String(length=64), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('override_approved_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id', 'provider_pr_id', name='uq_pr_repo_provider_pr_id')
    )
    with op.batch_alter_table('pull_requests', schema=None) as batch_op:
        batch_op.create_index('ix_pr_repo_state', ['repo_id', 'state'], unique=False)
        batch_op.create_index(batch_op.f('ix_pull_requests_author'), ['author'], unique=False)
        batch_op.create_index(batch_op.f('ix_pull_requests_merged_at'), ['merged_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pull_requests_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_pull_requests_repo_id'), ['repo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pull_requests_state'), ['state'], unique=False)

    op.create_table('repository_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repo_id', sa.String(length=36), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('pr_count', sa.Integer(), nullable=False),
    sa.Column('avg_health_score', sa.Float(), nullable=False),
    sa.Column('median_merge_time_minutes', sa.Float(), nullable=False),
    sa.Column('review_skipped_rate', sa.Float(), nullable=False),
    sa.Column('ci_failure_rate', sa.Float(), nullable=False),
    sa.Column('avg_review_quality_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id', 'period_start', name='uq_metric_repo_period')
    )
    with op.batch_alter_table('repository_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repository_metrics_repo_id'), ['repo_id'], unique=False)

    op.create_table('analysis_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pr_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pr_id'], ['pull_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_runs_pr_id'), ['pr_id'], unique=False)

    op.create_table('pr_checks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pr_id', sa.String(length=36), nullable=False),
    sa.Column('check_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pr_id'], ['pull_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pr_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pr_checks_pr_id'), ['pr_id'], unique=False)

    op.create_table('pr_diffs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pr_id', sa.String(length=36), nullable=False),
    sa.Column('files_changed', sa.Integer(), nullable=False),
    sa.Column('additions', sa.Integer(), nullable=False),
    sa.Column('deletions', sa.Integer(), nullable=False),
    sa.Column('files_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pr_id'], ['pull_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pr_diffs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pr_diffs_pr_id'), ['pr_id'], unique=True)

    op.create_table('pr_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pr_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('lines_commented', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pr_id'], ['pull_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pr_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pr_reviews_pr_id'), ['pr_id'], unique=False)

    op.create_table('analysis_scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('analysis_run_id', sa.String(length=36), nullable=False),
    sa.Column('pr_id', sa.String(length=36), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('review_quality_score', sa.Float(), nullable=False),
    sa.Column('merge_readiness', sa.Float(), nullable=False),
    sa.Column('score_breakdown_json', sa.JSON(), nullable=False),
    sa.Column('blocking_reason', sa.Text(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['pr_id'], ['pull_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_scores_analysis_run_id'), ['analysis_run_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_analysis_scores_pr_id'), ['pr_id'], unique=False)

    op.create_table('analysis_signals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('analysis_run_id', sa.String(length=36), nullable=False),
    sa.Column('signal_name', sa.String(length=128), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('exceeds_threshold', sa.Boolean(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_signals_analysis_run_id'), ['analysis_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_signals_signal_name'), ['signal_name'], unique=False)

    op.create_table('pr_narratives',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pr_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_run_id', sa.String(length=36), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=False),
    sa.Column('ai_recommendation', sa.Text(), nullable=False),
    sa.Column('ai_model', sa.String(length=64), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('was_accurate', sa.Boolean(), nullable=True),
    sa.Column('feedback_explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['pr_id'], ['pull_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pr_narratives', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pr_narratives_pr_id'), ['pr_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pr_narratives', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pr_narratives_pr_id'))

    op.drop_table('pr_narratives')
    with op.batch_alter_table('analysis_signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_signals_signal_name'))
        batch_op.drop_index(batch_op.f('ix_analysis_signals_analysis_run_id'))

    op.drop_table('analysis_signals')
    with op.batch_alter_table('analysis_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_scores_pr_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_scores_analysis_run_id'))

    op.drop_table('analysis_scores')
    with op.batch_alter_table('pr_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pr_reviews_pr_id'))

    op.drop_table('pr_reviews')
    with op.batch_alter_table('pr_diffs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pr_diffs_pr_id'))

    op.drop_table('pr_diffs')
    with op.batch_alter_table('pr_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pr_checks_pr_id'))

    op.drop_table('pr_checks')
    with op.batch_alter_table('analysis_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_runs_pr_id'))

    op.drop_table('analysis_runs')
    with op.batch_alter_table('repository_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repository_metrics_repo_id'))

    op.drop_table('repository_metrics')
    with op.batch_alter_table('pull_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pull_requests_state'))
        batch_op.drop_index(batch_op.f('ix_pull_requests_repo_id'))
        batch_op.drop_index(batch_op.f('ix_pull_requests_provider'))
        batch_op.drop_index(batch_op.f('ix_pull_requests_merged_at'))
        batch_op.drop_index(batch_op.f('ix_pull_requests_author'))
        batch_op.drop_index('ix_pr_repo_state')

    op.drop_table('pull_requests')
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repositories_provider'))

    op.drop_table('repositories')
    # ### end Alembic commands ###
